name: No Duplication beyond 3 lines

on: [push, pull_request]

jobs:
  nodups:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install jscpd
      run: sudo npm install -g jscpd

    - name: Check duplications
      run: jscpd --ignore "**/**test_BMS_ReadConsole.c,**/**test_BMS_Operations.c,**/**test_BMS_ProcessSensorValues.c,**/**test_BMS_receiver.c" --min-lines 3 --min-tokens 35 --threshold 0