name: No Duplication beyond 3 lines

on: [push, pull_request]

jobs:
  nodups:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install jscpd
      run: sudo npm install -g jscpd

    - name: Check duplications
      run: jscpd --ignore "BMS_Receiver_src/test_BMS_ReadConsole.c, BMS_Receiver_src/test_BMS_ProcessSensorValues.c, BMS_Receiver_src/test_BMS_Operations.c, BMS_Receiver_src/test_BMS_receiver.c" --min-lines 3 --min-tokens 35 --threshold 0